--N7 TEAM PROJECT
--ERP DB

--테이블 관련
-->>홈페이지 테이블

--상담게시판
CREATE TABLE CONSULTING_BOARD(
  CB_NUM NUMBER(5,0) NOT NULL,
  CB_TYPE NCHAR(1) NOT NULL,
  CB_WRITER NVARCHAR2(20) NOT NULL,
  CB_PASSWORD NVARCHAR2(20) NOT NULL,
  CB_TITLE NVARCHAR2(30) NOT NULL,
  CB_CONTENTS NCLOB NOT NULL,
  CONSTRAINT CB_NUM_PK PRIMARY KEY (CB_NUM)
);

--상담게시판 답글
CREATE TABLE BOARD_REPLY(
  BR_NUM NUMBER(5,0) NOT NULL,
  BR_CONTENTS NCLOB NOT NULL,
  CONSTRAINT BR_NUM_FK FOREIGN KEY (BR_NUM) REFERENCES CONSULTING_BOARD (CB_NUM)
);

--회사
CREATE TABLE COMPANY(
  C_CODE NVARCHAR2(20) NOT NULL,
  C_NAME NVARCHAR2(30) NOT NULL,
  C_CEO NVARCHAR2(10) NOT NULL,
  C_PHONENUM NVARCHAR2(11) NOT NULL,
  C_KIND NVARCHAR2(20) NOT NULL, --업태
  C_KIND2 NVARCHAR2(20) NOT NULL, --종류
  C_ADDR NVARCHAR2(50) NOT NULL,
  C_VALUE NVARCHAR2(20) NOT NULL,
  C_MONEY NUMBER(15, 0) NOT NULL,
  CONSTRAINT C_CODE_PK PRIMARY KEY (C_CODE)
);
--회사없이 가입할경우 기본값 입력되기 위한 더미데이터(홈페이지 회사)
INSERT INTO COMPANY
  VALUES('N7', 'N7PROJECT', 'N7', '01011112222', 'ERP', 'ERP',
  'INCHEON', 'VALUE', '0');

--홈페이지회원
CREATE TABLE MEMBER(
  M_ID NVARCHAR2(20) NOT NULL,
  M_PW NVARCHAR2(20) NOT NULL,
  M_NAME NVARCHAR2(10) NOT NULL,
  M_ADDRESS NVARCHAR2(50) NOT NULL,
  M_PHONENUM NVARCHAR2(11) NOT NULL, -- 01012345678형식(하이픈없음)
  M_PHOTO NVARCHAR2(100) NOT NULL,
  M_BIRTH NVARCHAR2(20) NOT NULL, --DEFAULT SYSDATE 사용하지않아서 편한 NVARCHAR2(20)F형식으로 함
  M_EMAIL NVARCHAR2(40) NOT NULL,
  M_GRADE NCHAR(1) NOT NULL,
  M_CCODE NVARCHAR2(20) NOT NULL DEFAULT 'N7',
  CONSTRAINT M_ID_PK PRIMARY KEY (M_ID),
  CONSTRAINT M_CCODE_FK FOREIGN KEY (M_CCODE) REFERENCES COMPANY (C_CCODE)
);

--회사 ERP 기능
CREATE TABLE ERP_FUNCTION(
  F_CCODE NVARCHAR2(20) NOT NULL,
  F_FUNCTIONS NVARCHAR2(20) NOT NULL,
  CONSTRAINT F_CCODE_FK NVARCHAR2(20) FOREIGN KEY (F_CCODE) REFERENCES COMPANY (C_CCODE)
);


-->>ERP기능 테이블
-->>>필수테이블

--인사카드
CREATE TABLE HR_CARD(
  HC_HRCODE NVARCHAR2(20) NOT NULL, --HC_JOINDATE + SEQ 로 자동생성
  HC_CCODE NVARCHAR2(20) NOT NULL,
  HC_ID NVARCHAR2(20) NOT NULL,
  HC_DEPT NVARCHAR2(20) NOT NULL,
  HC_POSITION NVARCHAR2(20) NOT NULL,
  HC_JOINDATE NVARCHAR2(20) NOT NULL,
  HC_WORK NCHAR(1) NOT NULL DEFAULT 0,
  HC_STATUS NCHAR(1) NOT NULL DEFAULT 0,
  HC_HOLYNUM NUMBER(2,0) NOT NULL DEFAULT 0,
  CONSTRAINT HC_HRCARD_PK PRIMARY KEY (HC_HRCODE, HC_CCODE),
  CONSTRAINT HC_HRCARD_FK1 FOREIGN KEY (HC_ID) REFERENCES MEMBER (M_ID),
  CONSTRAINT HC_HRCARD_FK2 FOREIGN KEY (HC_DEPT, HC_POSITION) REFERENCES HR_DEPT (HD_DEPT, HD_POSITION)
);

--부서/직책
CREATE TABLE HR_DEPT(
  HD_DEPT NVARCHAR2(20) NOT NULL,
  HD_POSITION NVARCHAR2(20) NOT NULL,
  HD_CCODE NVARCHAR2(20) NOT NULL,
  HD_PAY NUMBER,
  CONSTRAINT HC_DEPT_PK PRIMARY KEY (HD_DEPT, HD_POSITION),
  CONSTRAINT HC_DEPT_FK FOREIGN KEY (HD_CCODE) REFERENCES COMPANY (C_CCODE)
)

--사원 권한/기능
CREATE TABLE HR_AUTORITY(
  HAT_HRCODE NVARCHAR2(20) NOT NULL,
  HAT_CCODE NVARCHAR2(20) NOT NULL,
  HAT_AUTH NVARCHAR2(20) NOT NULL,
  CONSTRAINT HR_AUTORITY_FK FOREIGN KEY (HAT_HRCODE, HAT_CCODE) REFERENCES HR_CARD (HC_HRCODE, HC_CCODE)
);

--결재문서양식
CREATE TABLE APPROVALDOCU(
  AP_DOCUNUM NVARCHAR2(10) NOT NULL, --NCHAR(5)였는데 넉넉하게 바꿈
  AP_CCODE NVARCHAR2(20) NOT NULL,
  AP_DOCUNAME NVARCHAR2(20) NOT NULL,
  AP_FROMAPPROVER NVARCHAR2(20) NOT NULL,
  AP_TOAPPROVER NVARCHAR2(20) NOT NULL,
  AP_DATE DATE NOT NULL DEFAULT SYSDATE,
  AP_STATUS NCHAR(1) NOT NULL DEFAULT 0,
  CONSTRAINT APPROVALDOCU_PK PRIMARY KEY (AP_DOCUNUM, AP_CCODE),
  CONSTRAINT APPROVALDOCU_FK FOREIGN KEY (AP_CCODE) REFERENCES COMPANY (C_CCODE)
);


-->>>인사기능

--학력
CREATE TABLE HR_ACADEMIC(
  HAC_NUM NUMBER(5,0) NOT NULL,
  HAC_CCODE NVARCHAR2(20) NOT NULL,
  HAC_HRCODE NVARCHAR2(20) NOT NULL,
  HAC_SCHOOL NVARCHAR2(20) NOT NULL,
  HAC_MAJOR NVARCHAR2(20) NOT NULL,
  HAC_YEAR NVARCHAR2(20) NOT NULL,
  CONSTRAINT HR_ACADEMIC_PK PRIMARY KEY (HAC_NUM, HAC_CCODE),
  CONSTRAINT HR_ACADEMIC_FK FOREIGN KEY (HAC_CCODE, HAC_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);


--이력
CREATE TABLE HR_CAREER(
  HCR_NUM NUMBER(5,0) NOT NULL,
  HCR_CCODE NVARCHAR2(20) NOT NULL,
  HCR_HRCODE NVARCHAR2(20) NOT NULL,
  HCR_NAME NVARCHAR2(20) NOT NULL,
  HCR_STARTPERIOD NVARCHAR2(20) NOT NULL,
  HCR_ENDPERIOD NVARCHAR2(20) NOT NULL,
  HCR_POSITION NVARCHAR2(20) NOT NULL,
  HCR_CONTENT NCLOB,
  CONSTRAINT HR_CAREER_PK PRIMARY KEY (HCR_NUM, HCR_CCODE, HCR_HRCODE),
  CONSTRAINT HR_CAREER_FK FOREIGN KEY (HCR_CCODE, HCR_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);

--자격증
CREATE TABLE HR_CERTIFICATION(
  HCT_NUM NUMBER(5,0) NOT NULL,
  HCT_CCODE NVARCHAR2(20) NOT NULL,
  HCT_HRCODE NVARCHAR2(20) NOT NULL,
  HCT_NAME NVARCHAR2(20) NOT NULL,
  HCT_AGENCY NVARCHAR2(20) NOT NULL,
  HCT_DATE NVARCHAR2(20) NOT NULL,
  CONSTRAINT HR_CERTIFICATION_PK PRIMARY KEY (HCT_NUM, HCT_CCODE),
  CONSTRAINT HR_CERTIFICATION_FK FOREIGN KEY (HCT_CCODE, HCT_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);


-->>>급여
--급여명세서
CREATE TABLE HR_PAYROLL(
  HP_PAYDATE NVARCHAR2(20) NOT NULL,
  HP_CCODE NVARCHAR2(20) NOT NULL,
  HP_HRCODE NVARCHAR2(20) NOT NULL,
  HP_TAX NUMBER(15,0),
  HP_INCEN NUMBER(15,0),
  HP_INSURANCE NUMBER(15,0),
  HP_REALMONEY NUMBER(15,0) NOT NULL,
  CONSTRAINT HR_PAYROLL_PK PRIMARY KEY (HP_PAYDATE, HP_CCODE, HP_HRCODE),
  CONSTRAINT HR_PAYROLL_FK FOREIGN KEY (HP_CCODE, HP_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);

-->>>근태
--출/퇴근테이블
CREATE TABLE HR_ATTANDENCE(
  HA_CCODE NVARCHAR2(20) NOT NULL,
  HA_HRCODE NVARCHAR2(20) NOT NULL,
  HA_STARTTIME NVARCHAR2(20) NOT NULL,
  HA_ENDTIME NVARCHAR2(20) NOT NULL,
  CONSTRAINT HR_ATTANDENCE_FK FOREIGN KEY (HA_CCODE, HA_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);

--휴가신청
CREATE TABLE HR_APPLYHOLIDAY(
  HAP_DOCUNUM NVARCHAR2(10) NOT NULL, --문서번호 겸 휴가신청번호
  HAP_CCODE NVARCHAR2(20) NOT NULL,
  HAP_HRCODE NVARCHAR2(20) NOT NULL,
  HAP_DOCUNAME NVARCHAR2(20) NOT NULL,
  HAP_FROMAPPROVER NVARCHAR2(20) NOT NULL,
  HAP_TOAPPROVER NVARCHAR2(20) NOT NULL,
  HAP_APPLYDATE DATE NOT NULL DEFAULT SYSDATE, --문서신청일
  HAP_TYPE NVARCHAR2(20) NOT NULL, --휴가타입
  HAP_REASON NCLOB,
  HAP_STARTDAY NVARCHAR2(20) NOT NULL,
  HAP_ENDDAY NVARCHAR2(20) NOT NULL,
  HAP_STATUS NCHAR(1) NOT NULL DEFAULT 0,
  CONSTRAINT HR_APPLYHOLIDAY_PK PRIMARY KEY (HAP_DOCUNUM, HAP_CCODE),
  CONSTRAINT HR_APPLYHOLIDAY_FK1 FOREIGN KEY (HAP_DOCUNUM) REFERENCES APPROVALDOCU (AP_DOCUNUM),
  CONSTRAINT HR_APPLYHOLIDAY_FK2 FOREIGN KEY (HAP_CCODE, HAP_HRCODE) REFERENCES HR_CARD (HC_CCODE, HC_HRCODE)
);
