/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-17 00:13:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class membermanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/J:/erpn7/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/N7_ERPProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595218327510L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<!--\r\n");
      out.write("Design by TEMPLATED\r\n");
      out.write("http://templated.co\r\n");
      out.write("Released for free under the Creative Commons Attribution License\r\n");
      out.write("\r\n");
      out.write("Name       : UpRight\r\n");
      out.write("Description: A two-column, fixed-width design with dark color scheme.\r\n");
      out.write("Version    : 1.0\r\n");
      out.write("Released   : 20130526\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"/erp/css/default.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\" />\r\n");
      out.write("\t\t<link href=\"img/favicon.png\" rel=\"icon\" />\r\n");
      out.write("  <link href=\"img/apple-touch-icon.png\" rel=\"apple-touch-icon\" />\r\n");
      out.write("  <link href=\"lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"lib/icomoon/icomoon.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=1a9e4h5a1u&callback=initMap\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("\t<!--[if IE 6]>\r\n");
      out.write("<link href=\"default_ie6.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t<style>\r\n");
      out.write(".button {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#desc {\r\n");
      out.write("margin-left: 200px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: bolder;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\" class=\"container\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"/erp/\">N7 ERP SYSTEM</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"/erp/companymanager\" accesskey=\"3\" title=\"\">회사 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"/erp/membermanager\" accesskey=\"4\" title=\"\">회원 관리</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"description\">\r\n");
      out.write("\t\r\n");
      out.write("\t회원관리페이지 <h1> 탈퇴누르면 delete 시키는게 아니라 상태코드를 'X' 로 바꿔둠!!!!</h1>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t검색기능 :\r\n");
      out.write("\t<input type=\"text\" id=\"m_id\"></input>\t<button id=\"searchbtn\">검색</button> </br>\r\n");
      out.write("\t<br></br>\r\n");
      out.write("\t여기 출력\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br></br></br><br></br>\r\n");
      out.write("\t<div id=\"management\">\r\n");
      out.write("\t선택 멤버를 \r\n");
      out.write("\t<select>\r\n");
      out.write("\t<option value=\"0\"> 0(일반회원)</option>\r\n");
      out.write("\t<option value=\"1\"> 1(ERP매니저)</option>\r\n");
      out.write("\t<option value=\"2\"> 2(ADMIN계정)</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t으로 \r\n");
      out.write("\t<input type='button' value='변경' onclick=\"changeGrade()\">\r\n");
      out.write("\t<input type='button' value='강제탈퇴' onclick=\"forceWithdrawal()\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction confirmcheck(){\r\n");
      out.write("\t\tif(confirm(\"정말 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar gradeArr=[];\r\n");
      out.write("\tfunction changeGrade(){\r\n");
      out.write("\t\tif(confirmcheck()){\r\n");
      out.write("\t\t\t$(\"input[name=chkbx]:checked\").each(function(){\r\n");
      out.write("\t\t\t\tvar $id = $(this).val();\r\n");
      out.write("\t\t\t\tvar $grade = $(\"select\").val();\r\n");
      out.write("\t\t\t\tgradeArr.push({m_id :$id, m_grade :$grade});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tconsole.log(gradeArr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgradeArr = JSON.stringify(gradeArr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/erp/rest/home/changegrade\",\r\n");
      out.write("\t\t\t\tdata:{jsonStr : gradeArr},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t}, error : function(err){\r\n");
      out.write("\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t//\tlocation.reload();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar forceArr = [];\r\n");
      out.write("\tfunction forceWithdrawal(){\r\n");
      out.write("\t\tif(confirmcheck()){\r\n");
      out.write("\t\t\t$(\"input[name=chkbx]:checked\").each(function(){\r\n");
      out.write("\t\t\t\tvar $id = $(this).val();\r\n");
      out.write("\t\t\t\tforceArr.push($id);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tconsole.log(forceArr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tforceArr = JSON.stringify(forceArr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/erp/rest/home/forcewithdrawal\",\r\n");
      out.write("\t\t\t\tdata:{jsonStr : forceArr},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tmethod:\"post\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t}, error : function(err){\r\n");
      out.write("\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("//\t\t\tlocation.reload();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction SearchFromId(m_id){\r\n");
      out.write("\t\tconsole.log(m_id);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/erp/rest/home/searchfromid\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tdata:{m_id : m_id},\r\n");
      out.write("\t\t\tmethod:\"get\",\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tlet str = \"\";\r\n");
      out.write("\t\t\t\tstr = \"<table>\"\r\n");
      out.write("\t\t\t\tfor(let i = 0 ; i<data.length ; i++){\r\n");
      out.write("\t\t\t\t\tstr += \"<tr class = '' id='\"+data[i].m_id+\"'>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='checkbox' id='chkbx' name='chkbx' value='\"+data[i].m_id+\"'></td>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td>\" + data[i].m_name + \"(\" + data[i].m_id +\")</td>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td>\" + data[i].m_ccode + \"</td>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td>\" + data[i].m_grade + \"</td>\";\r\n");
      out.write("\t\t\t\t\tstr += \"</tr>\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tstr += \"</table>\";\r\n");
      out.write("\t\t\t\t$(\"#container\").html(str);\r\n");
      out.write("\t\t\t}, error : function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tSearchFromId(\"\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#searchbtn\").click(function() {\r\n");
      out.write("\t\tSearchFromId($(\"#m_id\").val());\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
