/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-15 05:49:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.hr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hrModifyDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".modifyMode{\r\n");
      out.write("\tbackground-color: skyblue;\r\n");
      out.write("}\r\n");
      out.write(".registMode{\r\n");
      out.write("\tbackground-color:red;\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("width: 200px;\r\n");
      out.write("height: 200px;\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write(".info{\r\n");
      out.write("\theight:60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>인사카드 세부정보 / 수정</h1>\r\n");
      out.write("<div id=\"member\"></div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<div id=\"menu\"></div>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<form id=\"form\" method=\"post\">\r\n");
      out.write("<div id=\"hrDetailInfo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border='1px solid black'>\r\n");
      out.write("<div id=\"addRecord\"></div>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<input type='hidden' value='' id='current'>\r\n");
      out.write("<input type='button' value='추가하기' onclick='addRecord()' id='addRecordBtn'>\r\n");
      out.write("<br>\r\n");
      out.write("<input type='button' value='수정하기' onclick='changeMode()' id='changeBtn'>\r\n");
      out.write("<input type='submit' value='등록하기' disabled=\"disabled\" id='registBtn'>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var num;\r\n");
      out.write("var id = location.search.substr(4);\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/hr/memberfromid\",\r\n");
      out.write("\t\tdata:{m_id:id},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tcontentType : 'application/json',\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\tlet info = \"\";\r\n");
      out.write("\t\t\tinfo += '<span style=\"height:200px;\"><img src=\"/erp/upload/'+data.m_photo+'\"></span>&nbsp;'\r\n");
      out.write("\t\t\tinfo += '<span style=\"height:200px;\"><table style=\"width:500px\"><tr class=\"info\"><td id=\"m_name\">'+data.m_name+'</td><td id=\"m_gender\">'+data.m_gender+'</td></tr>';\r\n");
      out.write("\t\t\tinfo += '<tr class=\"info\"><td id=\"m_phonenum\">'+data.m_phonenum+'</td><td id=\"m_birth\">'+data.m_birth+'</td></tr>';\r\n");
      out.write("\t\t\tinfo += '<tr style=\"height:80px;\"><td id=\"m_address\" colspan=\"2\">'+data.m_address+'</td></tr></table></span>';\r\n");
      out.write("\t\t\t$(\"#member\").html(info);\r\n");
      out.write("\t\t},error : function(err){\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/hr/hrcodefromid\",\r\n");
      out.write("\t\tdata:{m_id:id},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tcontentType: 'application/json',\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tlet str=\"\";\r\n");
      out.write("\t\t\tstr+='<tr><td><a href=\"javascript:InCompanyInfo()\"> 사내정보 </a></td>';\r\n");
      out.write("\t\t\tif(data){\r\n");
      out.write("\t\t\t\tstr +='<td><a href=\"javascript:AcademicInfo()\"> 학력 </a></td>';\r\n");
      out.write("\t\t\t\tstr +='<td><a href=\"javascript:CareerInfo() \"> 이력 </a></td>';\r\n");
      out.write("\t\t\t\tstr +='<td><a href=\"javascript:CertificationInfo()\"> 자격증 </a></td>';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tstr+='</tr>';\r\n");
      out.write("\t\t\t$(\"#menu\").html(str);\r\n");
      out.write("\t\t}, error : function(err){\r\n");
      out.write("\t\t\tconsole.log(err);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tconsole.log(\"load\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("/* var str1 = Number(replaceAll($('.checkDate')[0].value,\"-\",\"\"));\r\n");
      out.write("var str2;\r\n");
      out.write("if($('.checkDate')[1].value!=''){\r\n");
      out.write("str2 = Number(replaceAll($('.checkDate')[1].value,\"-\",\"\"));\r\n");
      out.write("console.log(str1);\r\n");
      out.write("if(str1>str2){\r\n");
      out.write("   alert(\"종료일은 시작일보다 이전일 수 없습니다.\");\r\n");
      out.write("   return;\r\n");
      out.write("}\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function replaceAll(str, searchStr, replaceStr) {\r\n");
      out.write("    return str.split(searchStr).join(replaceStr);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write("function checkDateValue(val1, val2){\r\n");
      out.write("\tlet date1 = Number(replaceAll(val1.value, \"-\", \"\"));\r\n");
      out.write("\tlet date2 = Number(replaceAll(val2.value, \"-\", \"\"));\r\n");
      out.write("\tif(date1>date2){\r\n");
      out.write("\t\talert(\"종료일은 시작일보다 이전일 수 없습니다.\");\r\n");
      out.write("\t\tval2.value = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("function addRecord(){\r\n");
      out.write("\tlet str =\"\";\r\n");
      out.write("\tlet cntAc = 0;\r\n");
      out.write("\tlet cntCt = 0;\r\n");
      out.write("\tvar $current = $(\"#current\").val();\r\n");
      out.write("\tconsole.log(num);\r\n");
      out.write("\tif($current == 'Academic'){\r\n");
      out.write("\t\tstr += \"<tr id='test'><td><input type='text' name='hac_school' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='text' name='hac_major' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='date' name='hac_year' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='button' value='삭제' onclick='javascript:thisRowDel(this);'></td></tr>\";\r\n");
      out.write("\t}else if($current =='Certification'){\r\n");
      out.write("\t\tstr += \"<tr><td><input type='text' name='hct_name' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='text' name='hct_agency' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='date' name='hct_date' class='detailInfo'></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='button' value='삭제' onclick='javascript:thisRowDel(this);'></td></tr>\";\r\n");
      out.write("\t}else if($current =='Career'){\r\n");
      out.write("\t\tstr += \"<tr><td><input type='text' name='hcr_cname' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><input type='date' name='hcr_startperiod' id='chk\"+(num*2)+\"' class='detailInfo checkDate'><br>\";\r\n");
      out.write("\t\tstr += \"<input type='date' name='hcr_endperiod' id='chk\"+((num*2)+1)+\"' class='detailInfo checkDate' onchange='checkDateValue(chk\"+(num*2)+\", chk\"+((num*2)+1)+\")'></td>\"\r\n");
      out.write("\t\tstr += \"<td><input type='text' name='hcr_position' class='detailInfo'></td>\";\r\n");
      out.write("\t\tstr += \"<td><textarea rows='3' cols='20' name='hcr_content' class='detailInfo'></textarea></td>\"\r\n");
      out.write("\t\tstr += \"<td><input type='button' value='삭제' onclick='javascript:thisRowDel(this);'></td></tr>\";\r\n");
      out.write("\t\tnum++;\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#hrDetailInfo\").append(str);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function thisRowDel(row){\r\n");
      out.write("\tconsole.log(row);\r\n");
      out.write("\tlet tr = row.parentNode.parentNode;\r\n");
      out.write("\ttr.parentNode.removeChild(tr);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function changeMode(){\r\n");
      out.write("\tconsole.log($(\"#changeBtn\").attr('class'));\r\n");
      out.write("\tif($(\"#changeBtn\").attr('class')==\"mf\"){\r\n");
      out.write("\t\t$(\".detailInfo\").attr(\"readonly\", true).addClass(\"modifyMode\").removeClass(\"registMode\");\r\n");
      out.write("\t\t$(\"#registBtn\").attr(\"disabled\", false);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\".detailInfo\").removeAttr(\"readonly\").removeClass(\"modifyMode\").addClass(\"registMode\");\r\n");
      out.write("\t\t$(\"#registBtn\").attr(\"disabled\", true);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#changeBtn\").toggleClass(\"mf\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var formURL = \"/erp/hr\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function AcademicInfo(){\r\n");
      out.write("\t$(\"#form\").attr(\"action\", formURL + \"/newacademic/\" +id);\r\n");
      out.write("\t$(\"#current\").val(\"Academic\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/hr/academic\",\r\n");
      out.write("\t\tdata:{m_id:id},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tcontentType: 'application/json',\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tif(data.length==undefined){\r\n");
      out.write("\t\t\t\tvar arr = [data]\r\n");
      out.write("\t\t\t\tdata = arr;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tlet str =\"\";\r\n");
      out.write("\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\tstr += \"<td>학교/학위</td><td>전공</td><td>날짜</td></tr>\";\r\n");
      out.write("\t\t\tfor(let i = 0 ; i <data.length ; i++){\r\n");
      out.write("\t\t\tconsole.log(data[i].hac_year);\r\n");
      out.write("\t\t\tstr += \"<tr><td><input type='text' name='hac_school' class='detailInfo' value='\"+data[i].hac_school+\"' readonly></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='text' name='hac_major' class='detailInfo' value='\"+data[i].hac_major+\"' readonly></td>\";\r\n");
      out.write("\t\t\tstr += \"<td><input type='date' name='hac_year' class='detailInfo' value='\"+data[i].hac_year+\"' readonly>\";\r\n");
      out.write("\t\t\tstr += \"<input type='hidden' name='hac_num' value='\"+data[i].hac_num+\"'></td></tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tstr += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#hrDetailInfo\").html(str);\r\n");
      out.write("\t\t},error : function(err){\r\n");
      out.write("\t\t\t/* let str =\"\";\r\n");
      out.write("\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\tstr += \"<td>학교/학위</td><td>전공</td><td>날짜</td></tr>\";\r\n");
      out.write("\t\t\tstr += \"<tr><td><input type='text' name='hac_school' class='detailInfo'></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='text' name='hac_major' class='detailInfo'></td>\";\r\n");
      out.write("\t\t\tstr += \"<td><input type='date' name='hac_year' class='detailInfo'></td></tr>\";\r\n");
      out.write("\t\t\tstr += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#hrDetailInfo\").html(str); */\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function CertificationInfo(){\r\n");
      out.write("\t$(\"#form\").attr(\"action\", formURL + \"/newcertification/\" +id);\r\n");
      out.write("\t$(\"#current\").val(\"Certification\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/hr/certification\",\r\n");
      out.write("\t\tdata:{m_id:id},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tif(data.length==undefined){\r\n");
      out.write("\t\t\tvar arr = [data]\r\n");
      out.write("\t\t\tconsole.log(arr);\r\n");
      out.write("\t\t\tdata = arr;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tlet str =\"\";\r\n");
      out.write("\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\tstr += \"<td>자격증</td><td>발급처</td><td>발급일</td></tr>\";\r\n");
      out.write("\t\t\tfor(let i = 0 ; i <data.length ; i++){\r\n");
      out.write("\t\t\tstr += \"<tr><td><input type='text' name='hct_name' class='detailInfo' value='\"+data[i].hct_name+\"' readonly ></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='text' name='hct_agency' class='detailInfo' value='\"+data[i].hct_agency+\"' readonly ></td>\";\r\n");
      out.write("\t\t\tstr += \"<td><input type='date' name='hct_date' class='detailInfo' value='\"+data[i].hct_date+\"' readonly></td>\";\r\n");
      out.write("\t\t\tstr += \"<input type='hidden' name='hct_num' value='\"+data[i].hct_num+\"'></td></tr>\";\r\n");
      out.write("\t\t\t}str += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#hrDetailInfo\").html(str);\r\n");
      out.write("\t\t},error : function(err){\r\n");
      out.write("\t\t\t/* let str =\"\";\r\n");
      out.write("\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\tstr += \"<td>자격증</td><td>발급처</td><td>발급일</td></tr>\";\r\n");
      out.write("\t\t\tstr += \"<tr><td><input type='text' name='hct_name' class='detailInfo'></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='text' name='hct_agency' class='detailInfo'></td>\";\r\n");
      out.write("\t\t\tstr += \"<td><input type='date' name='hct_date' class='detailInfo' required pattern='\\d{4}-\\d{2}-\\d{2}'></td></tr>\";\r\n");
      out.write("\t\t\tstr += \"</table>\";\r\n");
      out.write("\t\t\t$(\"#hrDetailInfo\").html(str); */\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("function CareerInfo(){\r\n");
      out.write("\t$(\"#form\").attr(\"action\", formURL + \"/newcareer/\" +id);\r\n");
      out.write("\t$(\"#current\").val(\"Career\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/hr/career\",\r\n");
      out.write("\t\tdata:{m_id:id},\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod:\"get\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"안됨?\");\r\n");
      out.write("\t\t\tlet str =\"\";\r\n");
      out.write("\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\tstr += \"<td>회사/프로젝트명</td><td>기간</td><td>직책</td><td>내용</td></tr>\";\r\n");
      out.write("\t\t\tfor(let i=0; i<data.length ; i++){\r\n");
      out.write("\t\t\tstr += \"<tr><td><input type='text' name='hcr_cname' class='detailInfo' value='\"+data[i].hcr_cname+\"' readonly ></td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='date' name='hcr_startperiod' id='chk\"+(i*2)+\"'class='detailInfo checkDate' value='\"+data[i].hcr_startperiod+\"' readonly ><br>\"\r\n");
      out.write("\t\t\tstr += \"<input type='date' name='hcr_endperiod' id='chk\"+((i*2)+1)+\"' class='detailInfo checkDate' value='\"+data[i].hcr_endperiod+\"' readonly onchange='checkDateValue(chk\"+(i*2)+\", chk\"+((i*2)+1)+\")'> </td>\"\r\n");
      out.write("\t\t\tstr += \"<td><input type='text' name='hcr_position' class='detailInfo' value='\"+data[i].hcr_position+\"' readonly ></td>\";\r\n");
      out.write("\t\t\tstr += \"<td><textarea rows='3' cols='20' name='hcr_content' class='detailInfo' value='\"+data[i].hcr_content+\"'></textarea>\";\r\n");
      out.write("\t\t\tstr += \"<input type='hidden' name='hcr_num' value='\"+data[i].hcr_num+\"'></td></tr>'\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tstr+=\"</table>\";\r\n");
      out.write("\t\t\t$(\"#hrDetailInfo\").html(str);\r\n");
      out.write("\t\t\tnum=data.length;\r\n");
      out.write("\t\t},error : function(err){\r\n");
      out.write("\t\t\tconsole.log(err);\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("function InCompanyInfo(){\r\n");
      out.write("\t$(\"#form\").attr(\"action\", formURL + \"/newhrcard/\" +id);\r\n");
      out.write("\t$(\"#current\").val(\"HRCard\");\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl :\"/erp/rest/hr/deptlist\",\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tmethod :\"get\",\r\n");
      out.write("\t\tsuccess : function(deptList){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/erp/rest/hr/hrcard\",\r\n");
      out.write("\t\t\t\tdata:{m_id:id},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tmethod:\"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(deptList);\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tvar married =\"\";\r\n");
      out.write("\t\t\t\t\tvar status =\"\";\r\n");
      out.write("\t\t\t\t\tvar work=\"\";\r\n");
      out.write("\t\t\t\t\tif(data.hc_status==1){\r\n");
      out.write("\t\t\t\t\t\tstatus=\"근무\";\r\n");
      out.write("\t\t\t\t\t}else if(data.hc_status==0){\r\n");
      out.write("\t\t\t\t\t\tstatus=\"퇴근\"\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tstatus=\"휴가\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(data.hc_work==1){\r\n");
      out.write("\t\t\t\t\t\twork=\"재직\";\r\n");
      out.write("\t\t\t\t\t}else if(data.hc_work==2){\r\n");
      out.write("\t\t\t\t\t\twork=\"휴직\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\twork=\"퇴사\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tlet str =\"\";\r\n");
      out.write("\t\t\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td>사원코드</td><td>부서</td><td>직책</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<tr><td><input type='text' name='hc_code' value='\"+data.hc_hrcode+\"' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><select name='hc_dept' class='detailInfo'>\"\r\n");
      out.write("\t\t\t\t\t\tfor(let i = 0 ; i<deptList.deptList.length ; i++){\r\n");
      out.write("\t\t\t\t\t\t\tif(data.hc_dept===deptList.deptList[i]){\r\n");
      out.write("\t\t\t\t\t\t\t\tstr += \"<option value='\"+deptList.deptList[i]+\"' selected='selected'>\"+deptList.deptList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<option value='\"+deptList.deptList[i]+\"'>\"+deptList.deptList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tstr += \"</select></td><td><select name='hc_position' class='detailInfo'>\";\r\n");
      out.write("\t\t\t\t\t\tfor(let i = 0 ; i<deptList.positionList.length ; i++){\r\n");
      out.write("\t\t\t\t\t\t\tif(data.hc_position===deptList.positionList[i]){\r\n");
      out.write("\t\t\t\t\t\t\t\tstr += \"<option value='\"+deptList.positionList[i]+\"' selected='selected'>\"+deptList.positionList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<option value='\"+deptList.positionList[i]+\"'>\"+deptList.positionList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tstr += \"</select></td></tr><td colspan='3'>입사일</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td colspan='3'><input type='date' name='hc_joindate' value='\"+data.hc_joindate+\"' class='detailInfo' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<tr><td>현재 상태</td><td>재/휴직 상태</td><td>사용한 월차</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' value='\"+status+\"' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' value='\"+work+\"'readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' value='\"+data.hc_numholi+\"' readonly></td></tr></table>\";\r\n");
      out.write("\t\t\t\t\tconsole.log(data.hc_joindate);\r\n");
      out.write("\t\t\t\t\t$(\"#hrDetailInfo\").html(str);\r\n");
      out.write("\t\t\t\t},error : function(err){\r\n");
      out.write("\t\t\t\t\tconsole.log(deptList);\r\n");
      out.write("\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t\tlet str =\"\";\r\n");
      out.write("\t\t\t\t\tstr += \"<table border='1px solid black'><tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td>사원코드</td><td>부서</td><td>직책</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<tr><td><input type='text' name='hc_code' placeholder='---' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><select name='hc_dept' class='detailInfo'>\"\r\n");
      out.write("\t\t\t\t\tfor(let i = 0 ; i<deptList.deptList.length ; i++){\r\n");
      out.write("\t\t\t\t\t\tstr += \"<option value='\"+deptList.deptList[i]+\"'>\"+deptList.deptList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tstr += \"</select></td><td><select name='hc_position' class='detailInfo'>\";\r\n");
      out.write("\t\t\t\t\tfor(let i = 0 ; i<deptList.positionList.length ; i++){\r\n");
      out.write("\t\t\t\t\t\tstr += \"<option value='\"+deptList.positionList[i]+\"'>\"+deptList.positionList[i]+\"</option>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tstr += \"</select></td></tr><td colspan='3'>입사일</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td colspan='3'><input type='date' name='hc_joindate' class='detailInfo'></td></tr>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<tr><td>현재 상태</td><td>재/휴직 상태</td><td>사용한 월차</td></tr>\";\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' placeholder='---' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' placeholder='---' readonly></td>\"\r\n");
      out.write("\t\t\t\t\tstr += \"<td><input type='text' placeholder='---' readonly></td></tr></table>\";\r\n");
      out.write("\t\t\t\t\t$(\"#hrDetailInfo\").html(str);\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t},error : function(err){\r\n");
      out.write("\t\t\tconsole.log(err);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
