/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-17 07:10:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class approvalLine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/J:/erpn7/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/N7_ERPProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1595218327510L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>결재라인</title>\r\n");
      out.write("<style>\r\n");
      out.write("div {\r\n");
      out.write("\tborder: 1px gray dotted;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr, td {\r\n");
      out.write("\tborder: 1px gray dotted;\r\n");
      out.write("\twidth: auto%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main1 {\r\n");
      out.write("\twidth: 28%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main2 {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main3 {\r\n");
      out.write("\twidth: 5%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("#main4 {\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search {\r\n");
      out.write("\theight: 10px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tbackground-color: #3B77AF;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".addtable {\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\toverflow: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but{\r\n");
      out.write("margin-top: 110px;\r\n");
      out.write("margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("height:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>결재라인 주소록</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"main1\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr class=\"search\">\r\n");
      out.write("\t\t\t\t\t<td>주소록</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"Info\"></tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main2\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr class=\"search\">\r\n");
      out.write("\t\t\t\t\t<td colspan=\"5\">이름으로 찾기</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><input id=\"name\" type=\"text\" name=\"m_name\"></td>\r\n");
      out.write("\t\t\t\t\t<td><button id=\"namesc\">검색</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 45px;\">체크</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 70px;\">이름</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:112px;\">부서</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:48px;\">직급</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:214px;\">이메일</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tbody id=\"nameInfo\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"main3\"><br>\r\n");
      out.write("\t\t<button id=\"addapproval1\" class=\"but\">></button><br>\r\n");
      out.write("\t\t<button id=\"deleteCheck1\"><</button><br><br><br><br><br>\r\n");
      out.write("\t<button id=\"addapproval2\" class=\"but\">></button><br>\r\n");
      out.write("\t<button id=\"deleteCheck2\"><</button><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"main4\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t\t결재자<span id=\"cnt1\" style=\"color:green;\">0</span>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<div class=\"addtable\">\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<tr class=\"search\"><td>체크</td><td>이름</td><td>작급</td><td>부서</td></tr>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"addAp1\"></tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t\t참조<span id=\"cnt2\" style=\"color:green;\">0</span>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<div class=\"addtable\">\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<tr class=\"search\"><td>체크</td><td>이름</td><td>작급</td><td>부서</td></tr>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"addAp2\"></tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div><br>\r\n");
      out.write("\t<a  href=\"javascript:sendChildValue()\"><button>결제라인 등록</button></a>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var count1=0;\r\n");
      out.write("\r\n");
      out.write("function sendChildValue(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(count1==0){\r\n");
      out.write("\t\talert(\"선택한 사람이 없습니다\");\r\n");
      out.write("\t} else{\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar code1 = new Array();\r\n");
      out.write("\t//var code2 = new Array();\r\n");
      out.write("\tfor(var i =0; i<count1; i++){\r\n");
      out.write("\t\tcode1.push($(\".addname1\"+i).val());\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t url:\"/erp/rest/Account/approLinecom?code1=\"+code1,\r\n");
      out.write("\t\t type:'post',\r\n");
      out.write("\t\t datatype:'json',\r\n");
      out.write("\t\t success:function(data){\r\n");
      out.write("\t\t\t console.log(data);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\t opener.setChildValue(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t window.close();\r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t error:function(error){\r\n");
      out.write("\t\t\t console.log(error);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t}  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#deleteCheck1\").click(function() {\r\n");
      out.write("\tvar cnt = $(\"input[name='checknum']:checked\").length;\r\n");
      out.write("\tfor (var i = 0; i < $(\".check1\").length; i++) {\r\n");
      out.write("\t\tif ($(\".check1\")[i].checked == true) {\r\n");
      out.write("\t\t\t$(\".check1\")[i].parentElement.parentElement.remove();\r\n");
      out.write("\t\t\ti--;\r\n");
      out.write("\t\t\tcount1--;\r\n");
      out.write("\t\t\t$(\"#cnt1\").html(count1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("/* $(\"#deleteCheck2\").click(function() {\r\n");
      out.write("\tfor (var i = 0; i < $(\".check2\").length; i++) {\r\n");
      out.write("\t\tif ($(\".check2\")[i].checked == true) {\r\n");
      out.write("\t\t\t$(\".check2\")[i].parentElement.parentElement.remove();\r\n");
      out.write("\t\t\ti--;\r\n");
      out.write("\t\t\tcount2--;\r\n");
      out.write("\t\t\t$(\"#cnt2\").html(count2);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write(" */\r\n");
      out.write("\tvar list = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${aList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tconsole.log(list);\r\n");
      out.write("\tvar str = \"\";\r\n");
      out.write("\tfor (var i = 0; i < list.length; i++) {\r\n");
      out.write("\t\tstr += \"<tr><td><input name='checknum' type='checkbox' value=\"+list[i].hc_hrcode+\"></td><td>\"\r\n");
      out.write("\t\t\t\t+ list[i].m_name + \"(\" + list[i].m_email + \")\" + \"</td></tr>\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(\"#Info\").append(str);\r\n");
      out.write("\t  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(\"#namesc\").click(function() {\r\n");
      out.write("\t\tvar str='';\r\n");
      out.write("\t\t\t\t\t\tvar name = $(\"#name\").val();\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl : '/erp/rest/Account/searchName?name=' + name,\r\n");
      out.write("\t\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tfor ( var i in data.aList) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstr += \"<tr><td><input name='checknum' type='checkbox' value='\"+data.aList[i].hc_hrcode+\"'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstr += \"<td>\"+ data.aList[i].m_name+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstr += \"<td>\"+ data.aList[i].hc_dept+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstr += \"<td>\"+ data.aList[i].hc_position+ \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstr += \"<td>\"+ data.aList[i].m_email+ \"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#nameInfo\").html(str);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t   \r\n");
      out.write("\t$(\"#addapproval1\").click(function(){\r\n");
      out.write("\t\tif(count1==3){\r\n");
      out.write("\t\t\talert(\"3명이상  선택 할 수 없습니다.\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar cnt = $(\"input[name='checknum']:checked\").length;\r\n");
      out.write("\t\tvar arr = new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(cnt == 0){\r\n");
      out.write("\t\t\talert(\"선택한 이름이 없습니다\");\r\n");
      out.write("\t}else {\r\n");
      out.write("\t\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tarr.push($(this).attr('value'));\r\n");
      out.write("               //var code = $(this).attr('value');\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t\turl : '/erp/rest/Account/addApproval',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\tdata : 'ARR=' + arr + '&CNT=' + cnt,\r\n");
      out.write("\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t                    //console.log(code);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i in data.aList){\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<tr><td><input class='check1' type='checkbox'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td><input class='addname1\"+i+\"' type='text' value='\"+data.aList[i].hc_hrcode+\"' hidden='true'>\"+data.aList[i].m_name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td>\"+data.aList[i].hc_position+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td>\"+data.aList[i].hc_dept+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#addAp1\").append(str);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t/* for(var k=0; k<=count1; k++){\r\n");
      out.write("\t\t\t\t\t\t\t\tname[k]=$(\".addname1\"+k).val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\tcount1+=Number(cnt);\r\n");
      out.write("\t\t\t\t\t\t\t//console.log(name);\r\n");
      out.write("\t\t\t\t\t\t\t//console.log(count1);\r\n");
      out.write("\t\t\t\t\t     $(\"#cnt1\").html(count1);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//var name =[];\r\n");
      out.write("\t});\r\n");
      out.write("\t /*    var count2=0;\r\n");
      out.write("\t$(\"#addapproval2\").click(function(){\r\n");
      out.write("\t\tvar name =[];\r\n");
      out.write("\t\tvar cnt = $(\"input[name='checknum']:checked\").length;\r\n");
      out.write("\t\tvar arr = new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(cnt == 0){\r\n");
      out.write("\t\t\talert(\"선택한 이름이 없습니다\");\r\n");
      out.write("\t}else {\r\n");
      out.write("\t\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\tarr.push($(this).attr('value'));\r\n");
      out.write("               var code = $(this).attr('value');\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t\turl : '/erp/rest/Account/addApproval',\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\tdata : 'ARR=' + arr + '&CNT=' + cnt,\r\n");
      out.write("\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t                    console.log(code);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tfor(var j=0; j<=count; j++){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(code==$(\".addname\"+j).val()&&count!=0){\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"이미추가되었습니다\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{ \r\n");
      out.write("\t\t\t\t\t\t\tfor(var i in data.aList){\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<tr><td><input class='check2' type='checkbox'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td><input class='addname2\"+count2+\"' type='text' value='\"+data.aList[i].hc_hrcode+\"' hidden='true'>\"+data.aList[i].m_name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td>\"+data.aList[i].hc_position+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tstr+=\"<td>\"+data.aList[i].hc_dept+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#addAp2\").append(str);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t } \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t\tfor(var k=0; k<=count2; k++){\r\n");
      out.write("\t\t\t\t\t\t\t\tname[k]=$(\".addname2\"+k).val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(name);\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(count2);\r\n");
      out.write("\t\t\t\t\t     count2++;\r\n");
      out.write("\t\t\t\t\t     $(\"#cnt2\").html(count2);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror:function(error){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t    */\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
