/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-15 08:14:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comPany_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>거래처등록</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"js/jquery.serializeObject.js\"></script> -->\r\n");
      out.write("<style>\r\n");
      out.write("<\r\n");
      out.write("style>body, td, th, select, textarea {\r\n");
      out.write("\tfont-family: Nanum Gothic, Gulim, Arial, ms sans serif;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 50%;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: auto:\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#search {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#Info {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"mainhead\" class=\"main\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<!-- <form id=\"code\"> -->\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"code\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"codesearch\">코드검색</button>\r\n");
      out.write("\t                    <!-- </form> -->\r\n");
      out.write("\t                    <button type=\"button\" id=\"Alllist\">전체리스트</button>\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t                    <button type=\"button\" id=\"delete\">삭제</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<table id=\"Info\">\r\n");
      out.write("\t\t\t\t<tbody id=\"Tbody\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"maincontents\" class=\"main\">\r\n");
      out.write("\t\t<form id=\"comInfo\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">거래처코드</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_code\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 45px; background: #FFFFFF;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">거래처명</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_name\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">사업자번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"cl_comnum\" class=\"nolineEx\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">대표자명</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_ceo\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">담당자명</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_employee\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">전화번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_phone\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">핸드폰번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_phone2\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">팩스번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_fax\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF;\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">email</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"cl_email\" class=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"ime-mode: inactive; width: 145px; background: #FFFFFF;\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">우편번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_addrnum\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 80px; background: #FFFFFF;\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">주소</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" name=\"cl_addr\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 380px; background: #FFFFFF; -ms-ime-mode: active;\"><br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">업태</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_kind\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">종목</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_kind2\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">거래은행</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\"><input type=\"text\" name=\"cl_bank\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th3\">예금주</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th4\"><input type=\"text\" name=\"cl_bankholder\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 145px; background: #FFFFFF; -ms-ime-mode: active;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">계좌번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"cl_banknum\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\" style=\"width: 145px; background: #FFFFFF;\"></td>\r\n");
      out.write("\t\t\t\t\t\t<th>종사업장번호</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"cl_comnum2\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"noline00\" style=\"width: 145px; background: #FFFFFF;\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">유형</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"th2\" style=\"padding-left: 10px;\"><select\r\n");
      out.write("\t\t\t\t\t\t\tname=\"cl_kind3\" class=\"select1\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 60px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"매출\">매출</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"매입\">매입</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"th1\">메모</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"cl_memo\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 380px; height: 75px; background: #FFFFFF; -ms-ime-mode: active;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"insertcomlist\">저장</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t $(\"#Alllist\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/erp/rest/Account/serchcomlist',\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tcontentType : 'application/json; charset=UTF-8',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tvar List=\"\";\r\n");
      out.write("\t\t\t\tList+=\"<tr><th><input name='Allcheck' type='checkbox'></th><th>코드</th><th>거래처명</th><th>사업자(주민)번호</th><th>대표자명</th><th>업태</th><th>유형</th></tr>\";\r\n");
      out.write("\t\t\t\tfor ( var i in data.aList) {\r\n");
      out.write("\t\t\t\t\tList+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td><input type='checkbox' name='reportChkBxRow' value=\"+data.aList[i].cl_code+\"></td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_code + \"</td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_comnum + \"</td>\";\r\n");
      out.write("\t\t\t\t    List+=\"<td>\" + data.aList[i].cl_ceo + \"</td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind + \"</td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind3 + \"</td>\";\r\n");
      out.write("\t\t\t\t\tList+=\"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("                 $(\"#Tbody\").html(List);\r\n");
      out.write("                 $(\"input\").html(\"\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#codesearch\").click(function() {\r\n");
      out.write("\t\tvar code = $(\"#code\").val();\r\n");
      out.write("\t\tconsole.log(code);\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '/erp/rest/Account/searchcode',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : {code:code},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar List=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tList+=\"<tr><th><input type='checkbox'></th><th>코드</th><th>거래처명</th><th>사업자(주민)번호</th><th>대표자명</th><th>업태</th><th>유형</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor ( var i in data.aList) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td><input type='checkbox' name='reportChkBxRow' value=\"+data.aList[i].cl_code+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_code + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_comnum + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    List+=\"<td>\" + data.aList[i].cl_ceo + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind3 + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t                 $(\"#Tbody\").html(List);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t },\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});  \r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#insertcomlist\").click(function() {\r\n");
      out.write("\t\t\t\t\t\tvar obj = $(\"#comInfo\").serialize();\r\n");
      out.write("\t\t\t\t\t\t//var json = JSON.stringify(obj);\r\n");
      out.write("\t\t\t\t\t\t//console.log(json)\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '/erp/rest/Account/insertcomlist',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//contentType : 'application/json; charset=UTF-8',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : obj,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar List=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tList+=\"<tr><th><input type='checkbox'></th><th>코드</th><th>거래처명</th><th>사업자(주민)번호</th><th>대표자명</th><th>업태</th><th>유형</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor ( var i in data.aList) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td><input  type='checkbox' name='reportChkBxRow' value=\"+data.aList[i].cl_code+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_code + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_comnum + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    List+=\"<td>\" + data.aList[i].cl_ceo + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind3 + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tList+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t                 $(\"#Tbody\").html(List);\r\n");
      out.write("\t\t\t\t\t\t                 $(\"input\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#delete\").click(function(){\r\n");
      out.write("\t\t var cnt = $(\"input[name='reportChkBxRow']:checked\").length;\r\n");
      out.write("\t     var arr = new Array();\r\n");
      out.write("\t     \t$(\"input[name='reportChkBxRow']:checked\").each(function() {\r\n");
      out.write("\t            arr.push($(this).attr('value'));\r\n");
      out.write("\t            \r\n");
      out.write("\t        \t});\r\n");
      out.write("\t     \tif(cnt==0){\r\n");
      out.write("\t     \t\talert(\"선택된 내용이 없습니다\");\r\n");
      out.write("\t     \t}else{\r\n");
      out.write("\t\t//var json = JSON.stringify(arr);\r\n");
      out.write("\t     \t\t$.ajax({\r\n");
      out.write("\t     \t\t\turl:'/erp/rest/Account/deleteCom',\r\n");
      out.write("\t     \t\t\ttype:'post',\r\n");
      out.write("\t     \t\t\ttraditional : true,\r\n");
      out.write("\t     \t\t\t//contentType : 'application/json; charset=UTF-8',\r\n");
      out.write("\t     \t\t\tdata:'ARR='+arr+'&CNT='+cnt,\r\n");
      out.write("\t     \t\t\tdatatype:'json',\r\n");
      out.write("\t     \t\t\tsuccess:function(data){\r\n");
      out.write("\t     \t\t\t\tconsole.log(data);\r\n");
      out.write("\t     \t\t\t\tvar List=\"\";\r\n");
      out.write("\t\t\t\t\t\tList+=\"<tr><th><input type='checkbox'></th><th>코드</th><th>거래처명</th><th>사업자(주민)번호</th><th>대표자명</th><th>업태</th><th>유형</th></tr>\";\r\n");
      out.write("\t\t\t\t\t\tfor ( var i in data.aList) {\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td><input  type='checkbox' name='reportChkBxRow' value=\"+data.aList[i].cl_code+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_code + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_comnum + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t    List+=\"<td>\" + data.aList[i].cl_ceo + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"<td>\" + data.aList[i].cl_kind3 + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tList+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t                 $(\"#Tbody\").html(List);\r\n");
      out.write("\t\t                 $(\"input\").html(\"\");\r\n");
      out.write("\t     \t\t\t},\r\n");
      out.write("\t     \t\t\terror:function(error){\r\n");
      out.write("\t     \t\t\t\tconsole.log(error);\r\n");
      out.write("\t     \t\t\t}\r\n");
      out.write("\t     \t\t\t\r\n");
      out.write("\t     \t\t});\r\n");
      out.write("\t     \t}\r\n");
      out.write("\t     \tconsole.log(arr);\r\n");
      out.write("\t     \tconsole.log(cnt);\r\n");
      out.write("\t     \t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
