/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-09-15 08:13:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class openTable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script> -->\r\n");
      out.write("\t<!-- <script src=\"/js/jquery.serializeObject.js\"></script> -->\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("#cal {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-family: 굴림;\r\n");
      out.write("\tborder: 2px border-color:#3333FF;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body, div {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#comInfo {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#plusorminus {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".data {\r\n");
      out.write("\twidth: 168px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main2 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".data2 {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#testTable{\r\n");
      out.write("width:1300px;\r\n");
      out.write("overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("#ListTable{\r\n");
      out.write("width:1300px;\r\n");
      out.write("height: 300px;\r\n");
      out.write("overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("#grafe{\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("#grafeInfo{\r\n");
      out.write("float: left;\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write("#detaile{\r\n");
      out.write("float: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tstyle=\"width: auto; background-color: white-space; color: white; padding: 1%;\">\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><a href=\"#\" onclick=\"saleinsert()\"><button>매출/매입등록</button></a></span>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><a href=\"#\"\r\n");
      out.write("\t\t\tonclick=\"window.open('comPany','comlist','width=1400,height=700')\"><button>거래처등록</button></a></span>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><button id=\"getList\">매출/매입조회</button></span>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><button id=\"taxbill\">세금계산서인쇄</button></span>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><button id=\"saledetails\">거래명세표인쇄</button></span>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><button id=\"approval\">결재요청하기</button></span>\r\n");
      out.write(" \t\t<span style=\"padding-left: 5px\"><button type=\"button\" id=\"delete\">삭제</button></span>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: auto; background-color: #FFB2D9; color: white; padding: 1%;\">매출/매입\r\n");
      out.write("\t\t\t전표관리</div>\r\n");
      out.write("\t\t<span style=\"padding-left: 5px\"><input id=\"select\" type=\"text\" /></span>\r\n");
      out.write("\t\t<select id=\"choice\" name=\"s_saleSelect\">\r\n");
      out.write("\t\t\t<option value=\"num\">전표번호</option>\r\n");
      out.write("\t\t\t<option value=\"company\">거래처명</option>\r\n");
      out.write("\t\t\t<option value=\"employee\">입력자</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<button id=\"search2\" type=\"button\">검색</button>\r\n");
      out.write("\t\t매출<input onclick=\"getList('S')\" type='radio' name=\"sale\" value='S'>\r\n");
      out.write("\t\t매입<input onclick=\"getList('P')\" type='radio' name=\"sale\" value='P'>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- <form action=\"rest/saleinsert\" method=\"post\"> -->\r\n");
      out.write("\t\t<form id=\"saleInfo\">\r\n");
      out.write("\t\t<div id=\"comInfo\"\r\n");
      out.write("\t\t\tstyle=\"height: 80px; padding-top: 15px; background-color: #F8F7F7;\">\r\n");
      out.write("\t\t\t<table id=\"main2\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>전표번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" type=\"text\" value=\"자동생성\" readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t<td>종류</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select class=\"data\" name=\"s_num\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">--</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"S\">매출</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"P\">매입</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t<td>유형</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select class=\"data\" name=\"s_kind\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"과세\">과세</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"비과세\">비과세</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>거래처명</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" type=\"text\" name=\"s_company\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td>사업자번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" type=\"text\" name=\"s_comnum\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td>입력자</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" type=\"text\" name=\"s_employee\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- </form> -->\r\n");
      out.write("\t\t\t<button id=\"detaile\" type=\"button\">상세정보</button>\r\n");
      out.write("\t\t\t <span id='plusorminus'> \r\n");
      out.write("\t\t\t<input type=\"number\" id=\"qty\" min=\"1\" style=\"width: 64px;\"> \r\n");
      out.write("\t\t\t<button type=\"button\" id=\"addList\"> 행추가</button>\r\n");
      out.write("\t\t\t<button type=\"button\" id=\"deleteCheck\">삭제</button>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- <form id=\"saleInfodetaile\"> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div id=\"ListTable\" style=\"background-color: #ECEBEA;\">\r\n");
      out.write("\t\t\t<table id=\"testTable\"\r\n");
      out.write("\t\t\t\tsummary=\"Code page support in different versions of MS Windows.\"\r\n");
      out.write("\t\t\t\tborder=\"1\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>체크</td>\r\n");
      out.write("\t\t\t\t\t\t<td>품목</td>\r\n");
      out.write("\t\t\t\t\t\t<td>수량</td>\r\n");
      out.write("\t\t\t\t\t\t<td>단가(원)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>공급가액(원)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>부가세액(원)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>합계(원)</td>\r\n");
      out.write("\t\t\t\t\t\t<td>적요</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"tBody\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" class=\"check\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" type=\"text\" name=\"s_pkind\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"cnt\" class=\"data\" type=\"text\" name=\"s_cnt\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"price\" class=\"data\" type=\"text\" name=\"s_price\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"price2\" class=\"data\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"s_price2\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"tax\" class=\"data\" type=\"text\" name=\"s_tax\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"total\" class=\"data\" type=\"text\" name=\"s_total\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"data\" name=\"s_memo\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write(" \t\t<button type=\"button\" onclick=\"saleInsertInfo()\">등록</button>\r\n");
      out.write("\t\r\n");
      out.write("        \r\n");
      out.write(" \t\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#search2\").click(function(){\r\n");
      out.write("\tvar select = $(\"#select\").val();\r\n");
      out.write("\tvar choice = $(\"#choice\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:\"/erp/rest/Account/selectSearch\",\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\tdata:'select='+select+'&choice='+choice,\r\n");
      out.write("\t\tdatatype:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tif(data.sList!=''){\r\n");
      out.write("\t\t\tvar str = '';\r\n");
      out.write("\t\t\tstr += \"<tr id='colume'><td>체크</td><td>전표번호</td><td>유형</td><td>거래처명</td><td>사업자번호</td><td>입력날짜</td><td>입력자</td></tr>\"\r\n");
      out.write("\t\t\tfor ( var i in data.sList) {\r\n");
      out.write("\t\t\t\tstr += \"<tr><td><input name='checknum' type='checkbox' class='check' value='\"+data.sList[i].s_num+\"'></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_num' value=\"+data.sList[i].s_num+\"></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_kind' value=\"+data.sList[i].s_kind+\"></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_company' value=\"+data.sList[i].s_company+\"></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_comnum' value=\"+data.sList[i].s_comnum+\"></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_date' value=\"+data.sList[i].s_date+\"></td>\";\r\n");
      out.write("\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_employee' value=\"+data.sList[i].s_employee+\"></td></tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#testTable\").html(str);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"검색할 데이터가 없습니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(error){\r\n");
      out.write("\t\t\tconsole.log(error);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#detaile\").click(function() {\r\n");
      out.write("\tvar check = '';\r\n");
      out.write("$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\tcheck = $(this).attr('value');\r\n");
      out.write("\t\t\t\tconsole.log(check);\r\n");
      out.write("                if(check!=\"\"){\r\n");
      out.write("\t\t\t\t\twindow.open('/erp/Account/SaleDetaile?check=' + check,\r\n");
      out.write("\t\t\t\t\t\t\t'SaleDetaile', 'width=1400,height=700');\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("                \talert(\"체크한 항목이 없습니다\");\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function saleInsertInfo(){\r\n");
      out.write("       var obj = $(\"#saleInfo\").serialize();\r\n");
      out.write("       $.ajax({\r\n");
      out.write("    \t  url:'/erp/rest/Account/saleinsert',\r\n");
      out.write("    \t  type:'post',\r\n");
      out.write("    \t  data:obj,\r\n");
      out.write("    \t  success:function(data){\r\n");
      out.write("    \t\t  console.log(data);\r\n");
      out.write("    \t\t  alert(\"데이터입력성공\");\r\n");
      out.write("    \t\t  $(\"input\").val(\"\");\r\n");
      out.write("    \t  },\r\n");
      out.write("    \t  error:function(error){\r\n");
      out.write("    \t\t  console.log(error);\r\n");
      out.write("    \t\t  alert(\"데이터 입력실패\");\r\n");
      out.write("    \t  }\r\n");
      out.write("    \t  \r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#approval\").click(function(){\r\n");
      out.write("\tvar check = '';\r\n");
      out.write("\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\t\t\tcheck = $(this).attr('value');\r\n");
      out.write("\t      });\r\n");
      out.write("\t\t\t\t\t\tif(check==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"체크한 항목이 없습니다\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\turl:'/erp/rest/Account/comparecode?code='+check,\r\n");
      out.write("\t\t\t\t\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\t\t\t\t\tdatatype:'json',\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(data.sList.length==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"이미 결재요청된 데이터 입니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twindow.open('/erp/Account/acApproval?check='+check,'acApproval','width=1400,height=700');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror:function(error){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#addList\").click(function() {\r\n");
      out.write("\t\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < $(\"#qty\").val(); i++) {\r\n");
      out.write("\t\t\t\t\t\tstr += \"<tr><td><input type='checkbox' class='check'></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_pkind'/></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_cnt'/></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_price'/></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_price2'/></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_tax'/></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' type='text' name='s_total' /></td>\"\r\n");
      out.write("\t\t\t\t\t\tstr += \"<td><input class='data' name='s_memo' /></td></tr>\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#tBody\").append(str);\r\n");
      out.write("\t\t\t\t\t$(\"#qty\").val(1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" function saleinsert(){\r\n");
      out.write("\t//$(\"#comInfo\").attr(\"display\",\"inline-block\");\t\r\n");
      out.write("\t//$(\"#plusorminus\").attr(\"display\",\"inline-block\");\r\n");
      out.write("\t$(\"#testTable\").html(\"\");\r\n");
      out.write("\tvar str='';\r\n");
      out.write("\tstr += \"<thead><tr><td>체크</td><td>품목</td><td>수량</td><td>단가(원)</td><td>공급가액(원)</td><td>부가세액(원)</td><td>합계(원)</td><td>적요</td></tr></thead>\"\r\n");
      out.write("\tstr += \"<tbody id='tBody'><tr><td><input type='checkbox' class='check'></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_pkind'/></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_cnt'/></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_price'/></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_price2'/></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_tax'/></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' type='text' name='s_total' /></td>\"\r\n");
      out.write("\t\tstr += \"<td><input class='data' name='s_memo' /></td></tr></tbody>\"\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#testTable\").html(str);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t$(\"#taxbill\").click(function() {\r\n");
      out.write("\t\t\t\tvar check = '';\r\n");
      out.write("\t\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tcheck = $(this).attr('value');\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(check);\r\n");
      out.write("                            if(check!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\tif (check.indexOf(\"S\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.open('/erp/Account/taxbill?check=' + check,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'taxbillS', 'width=1400,height=700');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.open('/erp/Account/taxbill?check=' + check,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'taxbillP', 'width=1400,height=700');\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("                            }else{\r\n");
      out.write("                            \talert(\"체크한 항목이 없습니다\");\r\n");
      out.write("                            }\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#saledetails\").click(function() {\r\n");
      out.write("\t\t\t\tvar check = '';\r\n");
      out.write("\t\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tcheck = $(this).attr('value');\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(check);\r\n");
      out.write("                            if(check!=\"\"){\r\n");
      out.write("\t\t\t\t\t\t\tif (check.indexOf(\"P\")) {\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.open('/erp/Account/saledetails?check=' + check,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t'saledetails', 'width=1400,height=700');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"매입은 거래명세표를 발급할 수 없습니다\")\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("                            }else{\r\n");
      out.write("                            \talert(\"체크한 항목이 없습니다\");\r\n");
      out.write("                            }\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction getList(code) {\r\n");
      out.write("\t\t $(\"#comInfo\").attr(\"display\",\"none\");\r\n");
      out.write("\t\t $(\"#plusorminus\").attr(\"display\",\"none\");\r\n");
      out.write("\t\tconsole.log(code);\r\n");
      out.write("\t\t//var json = JSON.stringify(code);\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\turl : '/erp/rest/Account/getList?code=' + code,\r\n");
      out.write("\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\t\t\tstr += \"<tr id='colume'><td>체크</td><td>전표번호</td><td>유형</td><td>거래처명</td><td>사업자번호</td><td>입력날짜</td><td>입력자</td></tr>\"\r\n");
      out.write("\t\t\t\t\t\tfor ( var i in data.sList) {\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<tr><td><input name='checknum' type='checkbox' class='check' value='\"+data.sList[i].s_num+\"'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_num' value=\"+data.sList[i].s_num+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_kind' value=\"+data.sList[i].s_kind+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_company' value=\"+data.sList[i].s_company+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_comnum' value=\"+data.sList[i].s_comnum+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_date' value=\"+data.sList[i].s_date+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_employee' value=\"+data.sList[i].s_employee+\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#testTable\").html(str);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#getList\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#comInfo\").attr(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#plusorminus\").attr(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\turl : '/erp/rest/Account/getsaleList',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 'get',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstr += \"<tr id='colume'><td>체크</td><td>전표번호</td><td>유형</td><td>거래처명</td><td>사업자번호</td><td>입력날짜</td><td>입력자</td></tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfor ( var i in data.sList1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<tr><td><input name='checknum' type='checkbox' class='check' value='\"+data.sList1[i].s_num+\"' readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_num' value=\"+data.sList1[i].s_num+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_kind' value=\"+data.sList1[i].s_kind+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_pkind' value=\"+data.sList[i].s_pkind+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_cnt' value=\"+data.sList[i].s_cnt+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_price' value=\"+data.sList[i].s_price+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_price2' value=\"+data.sList[i].s_price2+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_tax' value=\"+data.sList[i].s_tax+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_company' value=\"+data.sList1[i].s_company+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_total' value=\"+data.sList[i].s_total+\"></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_comnum' value=\"+data.sList1[i].s_comnum+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_date' value=\"+data.sList1[i].s_date+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_employee' value=\"+data.sList1[i].s_employee+\" readonly></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//str += \"<td><input class='data2' type='text' name='s_memo' value=\"+data.sList[i].s_memo+\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$(\"#testTable\").html(str);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#deleteCheck\").click(function() {\r\n");
      out.write("\t\tfor (var i = 0; i < $(\".check\").length; i++) {\r\n");
      out.write("\t\t\tif ($(\".check\")[i].checked == true) {\r\n");
      out.write("\t\t\t\t$(\".check\")[i].parentElement.parentElement.remove();\r\n");
      out.write("\t\t\t\ti--;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#delete\").click(function() {\r\n");
      out.write("\t\t\t\t\t\tvar cnt = $(\"input[name='checknum']:checked\").length;\r\n");
      out.write("\t\t\t\t\t\tvar arr = new Array();\r\n");
      out.write("\t\t\t\t\t\t$(\"input[name='checknum']:checked\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t\tarr.push($(this).attr('value'));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tif (cnt == 0) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"선택된 내용이 없습니다\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : '/erp/rest/Account/deleteSale',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : 'ARR=' + arr + '&CNT=' + cnt,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdatatype : 'json',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstr += \"<tr id='colume'><td>체크</td><td>전표번호</td><td>유형</td><td>거래처명</td><td>사업자번호</td><td>입력날짜</td><td>입력자</td></tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor ( var i in data.sList) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<tr><td><input name='checknum' type='checkbox' class='check' value='\"+data.sList[i].s_num+\"'></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_num' value=\"+data.sList[i].s_num+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_kind' value=\"+data.sList[i].s_kind+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_company' value=\"+data.sList[i].s_company+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_comnum' value=\"+data.sList[i].s_comnum+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_date' value=\"+data.sList[i].s_date+\"></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<td><input class='data2' type='text' name='s_employee' value=\"+data.sList[i].s_employee+\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#testTable\").html(str);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
