/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-19 07:25:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.stock;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class setitemcode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"/erp/css/default.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<style>\r\n");
      out.write("#header {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#side_menu {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: bolder;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#side_menu #menuList {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tmargin-top: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#side_menu #menuList li {\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#description {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 1500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th, table {\r\n");
      out.write("\tborder: 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td, th {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("width: 100px;\r\n");
      out.write("height: 30px;\r\n");
      out.write("background-color: #FFB2D9;\r\n");
      out.write("border:0px;\r\n");
      out.write("border-radius: 8px;\r\n");
      out.write("font-weight: bolder;\r\n");
      out.write("font-size: 14px;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("text-align: center;\r\n");
      out.write("color: red;\r\n");
      out.write("}\r\n");
      out.write(".span{\r\n");
      out.write("float: left;\r\n");
      out.write("width: 176px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a href=\"#\">N7 ERP SYSTEM</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" accesskey=\"4\" title=\"\">내 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" accesskey=\"2\" title=\"\">인사 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" accesskey=\"3\" title=\"\">영업 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" accesskey=\"5\" title=\"\">구매 관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"current_page_item\"><a href=\"#\" accesskey=\"6\"\r\n");
      out.write("\t\t\t\t\ttitle=\"\">자재 관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">회계 관리</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"side_menu\">\r\n");
      out.write("\t\t<ul id=\"menuList\">\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/setcategory\">분류명 작성</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/setitemcode\">품목 코드 작성</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/importlist\">입/출고 내역</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/importcheck\">입고 수정 및 확정</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/byitemdeallist\">품목별 거래현황</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/byitemstocklist\">품목별 자재현황</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/monthpayment\">월수불실적</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/erp/stock/exportstockcheck\">출고 양식</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"description\">\r\n");
      out.write("\t\t<h3>품목번호 작성</h3>\r\n");
      out.write("\t\t<form id=\"frm\">\r\n");
      out.write("\t\t<table style=\"border: 0px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">분류명</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input name=\"ct_name\" id=\"ct_name\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"50\" required=\"required\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">품목번호</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input name=\"it_ccode\" id=\"it_ccode\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"1\" required=\"required\"></td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">품목코드</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input id=\"it_code\" name=\"it_code\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"4\" required=\"required\"></td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">상품명</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input id=\"it_pname\" name=\"it_pname\" type=\"text\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">규격명</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input id=\"it_size\" name=\"it_size\" type=\"text\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\"></td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">단위</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input id=\"it_unit\" name=\"it_unit\" type=\"text\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"6\" required=\"required\"></td>\r\n");
      out.write("\t\t\t<tr><tr>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\">적정재고량</td>\r\n");
      out.write("\t\t\t\t<td style=\"border: 0px;\"><input id=\"it_pstock\" name=\"it_pstock\" type=\"number\" value=\"0\"></td>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"border: 0px;\"><button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tid=\"btn\">확정</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<span id='msg'></span><br><br>\r\n");
      out.write("\t\t<h3>분류명 내역</h3>\r\n");
      out.write("\t\t<button type=\"button\" id=\"modify\">수정</button>\r\n");
      out.write("\t<div id=\"smalldescription\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t//품목분류 출력\r\n");
      out.write("\titemCode('/erp/stock/getitemcode');\r\n");
      out.write("\t$('#btn').click(function(){\r\n");
      out.write("\t\tvar str = \" \";\r\n");
      out.write("\t\tvar flag = true;\r\n");
      out.write("\t\t//''검사\r\n");
      out.write("\t\tif($('#it_ccode').val()==''||$('#it_code').val()==''||$('#it_pname').val()==''||$('#it_size').val()==''||$('it_unit').val()==''){\r\n");
      out.write("\t\t\t$('#msg').html('값을 입력해주세요!');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//중복 검사\r\n");
      out.write("\t\tfor(var i = 0 ; i < $('.it_code').length;i++){\r\n");
      out.write("\t\t\tif($('#it_ccode').val()+\"-\"+$('#it_code').val()==$('.it_code')[i].value){\r\n");
      out.write("\t\t\t\t$('#msg').html('품목코드는 중복될 수 없습니다. 확인하고 다시 시도 해 주세요!');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('#msg').html('');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar data = $('#frm').serialize();\r\n");
      out.write("\t\tconsole.log(data);\r\n");
      out.write("\t\titemCode('/erp/stock/itemcodeconfirm',data);\r\n");
      out.write("\t\t$('input[id]').val(\"\");\r\n");
      out.write("\t\t$('#it_pstock').val(0);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction  itemCode(url,data) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tdata:data,\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tcontentType: \"application/x-www-form-urlencoded;charset=UTF-8\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tvar msg = '';\r\n");
      out.write("\t\t\t\tmsg+='<div class = \"span\">품목코드</div><div class = \"span\">상품명</div><div class = \"span\">규격명</div><div class = \"span\">단위</div><div class = \"span\">적정재고량</div><br>';\r\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < result.length;i++){\r\n");
      out.write("\t\t\t\t\tvar frm = document.createElement(\"form\"); \r\n");
      out.write("\t\t\t\t\tfrm.id = 'frm'+(i+1);\r\n");
      out.write("\t\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\t\tstr += '<input class=\"it_code\"  name=\"it_code\" type=\"text\" value=\"'\r\n");
      out.write("\t\t\t\t\t\t+ result[i].it_code\r\n");
      out.write("\t\t\t\t\t\t+ '\" readonly>'\r\n");
      out.write("\t\t\t\t\t\t+'<input class=\"it_pname\"   name=\"it_pname\" type=\"text\" value=\"'+result[i].it_pname+'\" readonly>'\r\n");
      out.write("\t\t\t\t\t\t+'<input class=\"it_size\"  name=\"it_size\" type=\"text\" value=\"'+result[i].it_size+'\" readonly>'\r\n");
      out.write("\t\t\t\t\t\t+'<input class=\"it_unit\" name=\"it_unit\" type=\"text\" value=\"'+result[i].it_unit+'\" readonly>'\r\n");
      out.write("\t\t\t\t\t\t+'<input class=\"it_pstock\" name=\"it_pstock\" type=\"number\" value=\"'+result[i].it_pstock+'\" readonly>'\r\n");
      out.write("\t\t\t\t\t\t+'<button type=\"button\" id=\"btn'+i+'\" onclick=\"modifyItemCode(\\''+(i+1)+'\\')\">확정</button>'\r\n");
      out.write("\t\t\t\t\t\t+ '<button type=\"button\" id=\"del'+i+'\"onclick=\"deleteItemCode(\\''+(i+1)+'\\')\">삭제</button>';\r\n");
      out.write("\t\t\t\t\t\tconsole.dir(frm);\r\n");
      out.write("\t\t\t\t\t\tfrm.innerHTML = str\r\n");
      out.write("\t\t\t\t\t\tmsg+=frm.outerHTML+'<br>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#smalldescription').html(msg);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//분류명, 품목번호 출력\r\n");
      out.write("\t$('#it_ccode').keyup(function() {\r\n");
      out.write("\t\tvar data = {ct_code:$('#it_ccode').val()}\r\n");
      out.write("\t\tcategory(data,'ct_code');\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#ct_name').keyup(function(){\r\n");
      out.write("\t\tvar data = {ct_name:$('#ct_name').val()}\r\n");
      out.write("\t\tcategory(data,'ct_name');\r\n");
      out.write("\t})\r\n");
      out.write("\tfunction category(data,data_id){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'/erp/stock/getct',\r\n");
      out.write("\t\t\tdata:data,\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tconsole.log('suc',data_id)\r\n");
      out.write("\t\t\t\tif(data_id=='ct_code'){\r\n");
      out.write("\t\t\t\t\t$('#ct_name').val(result);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#it_ccode').val(result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(err){\r\n");
      out.write("\t\t\t\tconsole.log('err',data_id)\r\n");
      out.write("\t\t\t\tif(data_id=='ct_code'){\r\n");
      out.write("\t\t\t\t\t$('#ct_name').val(err.responseText);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$('#it_ccode').val(err.responseText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//품목번호 수정\r\n");
      out.write("\tfunction modifyItemCode(i){\r\n");
      out.write("\t\tconsole.log('#frm'+i)\r\n");
      out.write("\t\tvar data = $('#frm'+i).serialize();\r\n");
      out.write("\t\tconsole.log(data);\r\n");
      out.write("\t\titemCode('/erp/stock/modifyitemcode',data);\r\n");
      out.write("\t}\r\n");
      out.write("\t//품목번호 삭제\r\n");
      out.write("\tfunction deleteItemCode(i) {\r\n");
      out.write("\t\tvar data = $('#frm'+i).serialize();\r\n");
      out.write("\t\titemCode('/erp/stock/deleteitemcode',data);\r\n");
      out.write("\t}\r\n");
      out.write("\t//readonly 해제\r\n");
      out.write("\t$('#modify').click(function () {\r\n");
      out.write("\t\t$('input[class]').attr(\"readonly\",false);\r\n");
      out.write("\t\t$('input[class=\"it_code\"]').attr(\"readonly\",true);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
